plc ex.7.3
goose-alt/bprd-assignments pull request #63
Opened 2022-10-13 14:42 UTC by Arneproductions

fixed #57

2022-10-17 10:50 UTC, amalieboegild requested changes

2022-10-17 10:50 UTC, amalieboegild commented on Assignment-06/README.md
> +## PLC-ex4.3
You mean 7.3, right?

2022-10-17 12:40 UTC, albe2669 requested changes
Without knowing, is all the files you have included necessary? I like what we've been doing where we just say what files we need, that doesn't actually need changing. Also, i think there may be some compiled files left over no?

2022-10-23 07:26 UTC, Arneproductions commented on Assignment-06/README.md
> +## PLC-ex4.3
Yes

2022-10-23 07:29 UTC, Arneproductions commented
> Without knowing, is all the files you have included necessary? I like what we've been doing where we just say what files we need, that doesn't actually need changing. Also, i think there may be some compiled files left over no?

Yes I do too... All the files in 7.1 and 7.2 will be removed when the branch created by @amalieboegild has been merged.

2022-10-27 09:04 UTC, amalieboegild approved these changes

2022-10-27 09:15 UTC, albe2669 approved these changes
Read thoroughly and well. Looks lovely

2022-10-27 09:17 UTC, merged